-- withdrawal_requests tablosu ve güvenli RLS politikaları
create table if not exists public.withdrawal_requests (
  id bigint generated by default as identity primary key,
  uid uuid,
  email text,
  artist_name text,
  amount numeric not null check (amount > 0),
  bank_name text,
  iban text,
  iban_account_holder text,
  requested_at timestamptz default now(),
  payout_date date,
  status text default 'pending' check (status in ('pending', 'processing', 'approved', 'paid', 'rejected')),
  paid_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.withdrawal_requests enable row level security;
grant select, insert on public.withdrawal_requests to authenticated;
grant update, delete on public.withdrawal_requests to authenticated;
grant usage, select on sequence public.withdrawal_requests_id_seq to authenticated;

drop policy if exists "artists can create own withdrawal requests" on public.withdrawal_requests;
drop policy if exists "artists can read own withdrawal requests" on public.withdrawal_requests;
drop policy if exists "admin can manage withdrawal requests" on public.withdrawal_requests;

create policy "artists can create own withdrawal requests"
on public.withdrawal_requests
for insert
to authenticated
with check (
  uid = auth.uid()
  and lower(email) = lower(auth.jwt() ->> 'email')
  and status = 'pending'
  and paid_at is null
);

create policy "artists can read own withdrawal requests"
on public.withdrawal_requests
for select
to authenticated
using (
  uid = auth.uid()
  or lower(email) = lower(auth.jwt() ->> 'email')
);

create policy "admin can manage withdrawal requests"
on public.withdrawal_requests
for all
to authenticated
using (
  exists (
    select 1 from public.admin_users
    where user_id = auth.uid() and active = true
  )
)
with check (
  exists (
    select 1 from public.admin_users
    where user_id = auth.uid() and active = true
  )
);

create index if not exists withdrawal_requests_email_created_idx
  on public.withdrawal_requests (lower(email), created_at desc);
create index if not exists withdrawal_requests_status_created_idx
  on public.withdrawal_requests (status, created_at desc);

notify pgrst, 'reload schema';
